### PR TITLE
Integration with YASPP project

### PR DESCRIPTION
**Pull request by dfsantamaria**
Modified SparqlQueryView.java and added SparqlQueryViewPanel.java. Added a dependency in POM file.

### CODE REVIEW

**Comment by dfsantamaria** [comment]
Ignore the netbeans config file.

**Comment by csnyulas** [comment]
Hi @dfsantamaria,

I know that you closed this pull request already, so I can't merge it. If you decide to do another pull request, though, can you please take care of these few things:
- don't commit the netbeans config file (which does not belong in the repo, as you have observed yourself already)
- can you please rename all references to **YASPP** or **yaspp** (or **YASSP**, see comment below) to something more generic, which is in line with other names in the SPARQL plugin? If you submit your code as part of our plugin, refering to it (or some components of it) as "yet another SPARQL plug-in for protege (or YASPP)" will not be accurate anymore. BTW, in case you would like to keep this as a separate plugin, please check all occurences of **YASSP** (observe double **S** instead of double **P**) and change it to **YASPP** (for example [here](https://github.com/dfsantamaria/YASPP/blob/sparqlPluginBased/pom.xml#L16))

**Comment by csnyulas** [comment]
Other than those comments, your pull request looks pretty nice! Thanks for your contribution!

**Comment by dfsantamaria** [comment]
Ok, tomorrow I correct these problems and submit a second pull.DanieleDaniele Francesco Santamaria, Ph.D. Student Ufficio 32, Blocco I, +39 095 738 3019 Department of Mathematics and Computer Science, University of Catania, Viale A.Doria, 6 - 95125 - Catania, Italy http://www.dmi.unict.it/~santamaria/ Il 10 ago 2017 10:57 PM, csnyulas <notifications@github.com> ha scritto:Other than those comments, your pull request looks pretty nice! Thanks for your contribution!

**Pull request closed without merging**
